import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['eslint', 'typescript', 'unicorn'],
  categories: {
    correctness: 'off',
  },
  env: {
    builtin: true,
    es2020: true,
    commonjs: true,
  },
  rules: {
    'typescript/await-thenable': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-confusing-void-expression': 'allow',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-floating-promises': 'off',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-promises': 'off',
    'typescript/no-misused-spread': 'allow',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-arguments': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unsafe-call': 'off',
    'typescript/no-unsafe-return': 'off',
    'typescript/no-unsafe-argument': 'off',
    'typescript/no-redundant-type-constituents': 'off',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-member-access': 'allow',
    'typescript/no-unsafe-type-assertion': 'warn',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/non-nullable-type-assertion-style': 'error',
    'typescript/only-throw-error': 'allow',
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-return-this-type': 'error',
    'typescript/promise-function-async': 'off',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/require-array-sort-compare': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/restrict-template-expressions': 'error',
    'typescript/return-await': 'off',
    'typescript/switch-exhaustiveness-check': 'off',
    'typescript/unbound-method': 'error',
    'typescript/use-unknown-in-catch-callback-variable': 'error',
    'constructor-super': 'error',
    'for-direction': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'allow',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        ignoreRestSiblings: true,
        destructuredArrayIgnorePattern: '^_',
      },
    ],
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    '@typescript-eslint/ban-ts-comment': 'error',
    'no-array-constructor': 'error',
    '@typescript-eslint/no-duplicate-enum-values': 'error',
    '@typescript-eslint/no-empty-object-type': 'off',
    '@typescript-eslint/no-extra-non-null-assertion': 'error',
    '@typescript-eslint/no-misused-new': 'error',
    '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
    '@typescript-eslint/no-require-imports': 'error',
    '@typescript-eslint/no-this-alias': 'error',
    '@typescript-eslint/no-unnecessary-type-constraint': 'error',
    '@typescript-eslint/no-unsafe-declaration-merging': 'error',
    '@typescript-eslint/no-unsafe-function-type': 'error',
    'no-unused-expressions': 'error',
    '@typescript-eslint/no-wrapper-object-types': 'error',
    '@typescript-eslint/prefer-as-const': 'error',
    '@typescript-eslint/prefer-namespace-keyword': 'error',
    '@typescript-eslint/triple-slash-reference': 'error',
    'no-var': 'error',
    'prefer-template': 'error',
    'no-duplicate-imports': 'error',
  },
  globals: {
    __dirname: 'readonly',
    __filename: 'readonly',
    AbortController: 'readonly',
    AbortSignal: 'readonly',
    AsyncDisposableStack: 'readonly',
    atob: 'readonly',
    Blob: 'readonly',
    BroadcastChannel: 'readonly',
    btoa: 'readonly',
    Buffer: 'readonly',
    ByteLengthQueuingStrategy: 'readonly',
    clearImmediate: 'readonly',
    clearInterval: 'readonly',
    clearTimeout: 'readonly',
    CloseEvent: 'readonly',
    CompressionStream: 'readonly',
    console: 'readonly',
    CountQueuingStrategy: 'readonly',
    crypto: 'readonly',
    Crypto: 'readonly',
    CryptoKey: 'readonly',
    CustomEvent: 'readonly',
    DecompressionStream: 'readonly',
    DisposableStack: 'readonly',
    DOMException: 'readonly',
    Event: 'readonly',
    EventTarget: 'readonly',
    fetch: 'readonly',
    File: 'readonly',
    FormData: 'readonly',
    Headers: 'readonly',
    MessageChannel: 'readonly',
    MessageEvent: 'readonly',
    MessagePort: 'readonly',
    navigator: 'readonly',
    Navigator: 'readonly',
    performance: 'readonly',
    Performance: 'readonly',
    PerformanceEntry: 'readonly',
    PerformanceMark: 'readonly',
    PerformanceMeasure: 'readonly',
    PerformanceObserver: 'readonly',
    PerformanceObserverEntryList: 'readonly',
    PerformanceResourceTiming: 'readonly',
    process: 'readonly',
    queueMicrotask: 'readonly',
    ReadableByteStreamController: 'readonly',
    ReadableStream: 'readonly',
    ReadableStreamBYOBReader: 'readonly',
    ReadableStreamBYOBRequest: 'readonly',
    ReadableStreamDefaultController: 'readonly',
    ReadableStreamDefaultReader: 'readonly',
    Request: 'readonly',
    Response: 'readonly',
    setImmediate: 'readonly',
    setInterval: 'readonly',
    setTimeout: 'readonly',
    structuredClone: 'readonly',
    SubtleCrypto: 'readonly',
    SuppressedError: 'readonly',
    TextDecoder: 'readonly',
    TextDecoderStream: 'readonly',
    TextEncoder: 'readonly',
    TextEncoderStream: 'readonly',
    TransformStream: 'readonly',
    TransformStreamDefaultController: 'readonly',
    URL: 'readonly',
    URLPattern: 'readonly',
    URLSearchParams: 'readonly',
    WebAssembly: 'readonly',
    WebSocket: 'readonly',
    WritableStream: 'readonly',
    WritableStreamDefaultController: 'readonly',
    WritableStreamDefaultWriter: 'readonly',
  },
  ignorePatterns: [
    '**/node_modules/',
    '**/dist/',
    '**/coverage/',
    '**/.next/',
    '**/out/',
    '**/*.d.ts',
    '**/*.d.mts',
  ],
  overrides: [
    {
      files: ['**/*.js'],
      rules: {
        '@typescript-eslint/no-var-requires': 'off',
      },
    },
    {
      files: ['**/*.spec.{ts,tsx}', '**/*.test.{ts,tsx}'],
      rules: {
        '@typescript-eslint/no-unnecessary-type-assertion': 'off',
        'no-unused-vars': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/unbound-method': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-return': 'off',
        'typescript/no-unsafe-argument': 'off',
      },
    },
  ],
});
